---
- name: Install Go via mise package manager role
  ansible.builtin.include_role:
    name: package_manager_mise
  vars:
    package_manager_mise_tools: "{{ tool_go_mise_tools }}"

- name: Install Go tools
  ansible.builtin.include_tasks: postinstall.yml
  when: tool_go_tools | length > 0
