---
- name: Add Go bin directory to PATH in bashrc
  ansible.builtin.blockinfile:
    path: "{{ tool_go_bashrc }}"
    marker: "# {mark} ANSIBLE MANAGED - go"
    block: |
      export PATH="{{ tool_go_gopath }}/bin:$PATH"
    create: true
    insertafter: EOF

- name: Add Go bin directory to PATH in zshrc
  ansible.builtin.blockinfile:
    path: "{{ tool_go_zshrc }}"
    marker: "# {mark} ANSIBLE MANAGED - go"
    block: |
      export PATH="{{ tool_go_gopath }}/bin:$PATH"
    create: true
    insertafter: EOF

- name: Install Go tools
  ansible.builtin.command:
    cmd: "go install {{ item }}"
  loop: "{{ tool_go_tools }}"
  register: tool_go_install_result
  changed_when: tool_go_install_result.rc == 0
  environment:
    GOPATH: "{{ ansible_facts['env']['HOME'] }}/go"
    PATH: "{{ ansible_facts['env']['HOME'] }}/go/bin:{{ ansible_facts['env']['PATH'] }}:/opt/homebrew/bin:/usr/local/bin"
