---
- name: Install browsers on Linux
  ansible.builtin.include_tasks: install-linux.yml
  when: ansible_facts["system"] == "Linux"

- name: Install browsers on macOS
  ansible.builtin.include_tasks: install-mac.yml
  when: ansible_facts["system"] == "Darwin"
