---
- name: Install VSCodium via Flatpak package manager role
  ansible.builtin.include_role:
    name: package_manager_flatpak
  vars:
    package_manager_flatpak_packages:
      - "{{ _vscodium_flatpak_id }}"
