---
- name: Add aliases to bashrc
  ansible.builtin.blockinfile:
    path: "{{ config_alias_bashrc }}"
    marker: "# {mark} ANSIBLE MANAGED - aliases"
    block: |
      {% for alias_line in config_alias_lines %}
      {{ alias_line }}
      {% endfor %}
    create: true
    insertafter: EOF
  when: config_alias_lines | length > 0

- name: Add aliases to zshrc
  ansible.builtin.blockinfile:
    path: "{{ config_alias_zshrc }}"
    marker: "# {mark} ANSIBLE MANAGED - aliases"
    block: |
      {% for alias_line in config_alias_lines %}
      {{ alias_line }}
      {% endfor %}
    create: true
    insertafter: EOF
  when: config_alias_lines | length > 0
