---
- name: Add aliases to shell configs
  ansible.builtin.blockinfile:
    path: "{{ rc_file.path }}"
    marker: "# {mark} ANSIBLE MANAGED - aliases"
    block: |
      {% for alias_line in config_alias_lines %}
      {{ alias_line }}
      {% endfor %}
    create: true
    insertafter: EOF
  loop: "{{ shell_rc_files }}"
  loop_control:
    loop_var: rc_file
  when: config_alias_lines | length > 0
