---
- name: Install Podman CLI and podman-compose via rpm-ostree package manager role
  ansible.builtin.include_role:
    name: package_manager_rpm_ostree
  vars:
    package_manager_rpm_ostree_packages: "{{ tool_podman_linux_rpm_ostree_packages }}"

- name: Install Podman Desktop via Flatpak package manager role
  ansible.builtin.include_role:
    name: package_manager_flatpak
  vars:
    package_manager_flatpak_packages: "{{ tool_podman_linux_flatpak_packages }}"
