---
tool_go_gopath: "{{ ansible_facts['env']['HOME'] }}/go"

tool_go_mise_tools:
  - go@latest
  - make@latest

tool_go_tools:
  - golang.org/x/tools/gopls@latest
  - github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  - golang.org/x/tools/cmd/goimports@latest
