---
tool_go_gopath: "{{ ansible_facts['env']['HOME'] }}/go"
tool_go_bashrc: "{{ ansible_facts['env']['HOME'] }}/.bashrc"
tool_go_zshrc: "{{ ansible_facts['env']['HOME'] }}/.zshrc"

tool_go_macos_brew_formulae:
  - go

tool_go_linux_dnf_packages:
  - golang

tool_go_tools:
  - golang.org/x/tools/gopls@latest
  - github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  - golang.org/x/tools/cmd/goimports@latest
