---
- name: Install Chromium on Linux
  ansible.builtin.include_tasks: install-linux.yml
  when: ansible_facts["system"] == "Linux"

- name: Install Chromium on macOS
  ansible.builtin.include_tasks: install-mac.yml
  when: ansible_facts["system"] == "Darwin"

- name: Configure Chromium postinstall on Linux
  ansible.builtin.include_tasks: postinstall-linux.yml
  when:
    - ansible_facts["system"] == "Linux"
    - tool_chromium_extensions | length > 0

- name: Configure Chromium postinstall on macOS
  ansible.builtin.include_tasks: postinstall-mac.yml
  when:
    - ansible_facts["system"] == "Darwin"
    - tool_chromium_extensions | length > 0
