---
- name: Remove quarantine attribute from Chromium.app
  ansible.builtin.command:
    cmd: xattr -dr com.apple.quarantine /Applications/Chromium.app
  changed_when: false
  failed_when: false
  when: not ansible_check_mode

- name: Ensure Chromium extension directory exists
  ansible.builtin.file:
    path: "{{ tool_chromium_macos_external_extensions_dir }}"
    state: directory
    mode: "0755"

- name: Install Chromium extension manifests
  ansible.builtin.copy:
    dest: "{{ tool_chromium_macos_external_extensions_dir }}/{{ item.chromium_id }}.json"
    mode: "0644"
    content: |
      {
        "external_update_url": "{{ item.chromium_update_url }}"
      }
  loop: "{{ tool_chromium_extensions }}"
