---
- name: Configure testcontainers to use rootless Podman socket
  ansible.builtin.copy:
    dest: "{{ ansible_facts['env']['HOME'] }}/.testcontainers.properties"
    mode: "0644"
    content: |
      docker.host=unix:///run/user/{{ ansible_user_uid }}/podman/podman.sock
      ryuk.disabled=true

- name: Ensure ~/.redhat directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.redhat"
    state: directory
    mode: "0755"

- name: Opt out of Quarkus usage analytics
  ansible.builtin.copy:
    dest: "{{ ansible_facts['env']['HOME'] }}/.redhat/io.quarkus.analytics.localconfig"
    mode: "0644"
    content: |
      {"disabled":true}
