---
- name: Install Ghostty from rpm-ostree on Linux
  ansible.builtin.include_tasks: install-linux.yml
  when: ansible_facts["system"] == "Linux"

- name: Install Ghostty from Homebrew on macOS
  ansible.builtin.include_tasks: install-mac.yml
  when: ansible_facts["system"] == "Darwin"

- name: Run shared Ghostty postinstall tasks
  ansible.builtin.include_tasks: postinstall.yml
  when: ansible_facts["system"] in ["Linux", "Darwin"]
